apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packet-capture
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: packet-capture
  template:
    metadata:
      labels:
        app: packet-capture
    spec:
      serviceAccountName: packet-capture
      containers:
      - name: controller
        image: antrea-packet-capture:dev
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: capture-dir
          mountPath: /captures
      volumes:
      - name: capture-dir
        emptyDir: {}

