apiVersion: v1
kind: Pod
metadata:
  name: annotest
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - |
      while true; do
        ping -c 1 8.8.8.8;
        sleep 1;
      done
